# root command
config: "./config.yaml"
key: "skill-vein-planet-neigh-envoi"
dsn: "root@/lineupTestDB"

# server command
port: ":5000"
static: "./public"
# jwt token expire time in minutes
time: 300

# import command
import: ./data/user.json

# create command
overwrite: false
